package fr.doranco.quizz;

public interface IQuizConstants {
       String PREF_KEY_USER_FIRSTNAME = "PREF_KEY_USER_FIRSTNAME";
       String PREF_KEY_USER_SCORE = "PREF_KEY_USER_SCORE";
       int QUIZ_ACTIVITY_REQUEST_CODE = 1;
       String EXTRA_SCORE_PARAM  = "EXTRA_SCORE_PARAM";
       String STATE_SCORE_BEFORE_ROTATION = "STATE_SCORE_BEFORE_ROTATION";
       String STATE_QUESTION_BEFORE_ROTATION = "STATE_QUESTION_BEFORE_ROTATION";
}
